### ISSUE TITLE
First Project/Commit

### ISSUE THREAD

**Issue by Faithful1** [BuildForSDGCohort2/Confyde-Frontend#4]

**Comment by jamesoyanna** [comment]
First Initial commit for project setup and deployment completed

**Comment by Faithful1** [comment]
This is completed and staging can be found on this endpoint
https://confyde-app.netlify.app/

**Comment by Faithful1** [comment]
Since this is just expected to be the first commit. I will close this issue

**Comment by Faithful1** [comment]
Since this is just expected to be the first commit. I will close this issue
